# Site settings
title: "Mostly .NET - Mostly for me"
email: loc.tan.vo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: loctanvo
github_username: loctanvo

# Build settings
markdown: kramdown

# Outputting
permalink: pretty
paginate_path: /page:num
timezone: Europe/Oslo

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
