# Site settings
title: "Mostly .NET - Mostly for me"
email: loc.tan.vo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Loc Tan Vo's personal website and blog. The blog posts are mostly technical,
  and mostly about .NET development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.loctanvo.com" # the base hostname & protocol for your site
twitter_username: loctanvo
github_username: loctanvo

# Build settings
markdown: kramdown
exclude: ['resources']

# Outputting
permalink: pretty
paginate_path: /page:num
timezone: Europe/Oslo

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"